# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

env:
  AZURE_WEBAPP_NAME: bletchley    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: './Views'      # set this to the path to your web app project, defaults to the repository root
  
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: 'Azure'
      url: 'ftp://waws-prod-ch1-019.ftp.azurewebsites.windows.net/site/wwwroot/Views' #${{ steps.deploy-to-webapp.outputs.webapp-url }}      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: deploy-to-webapp
        uses: actions/checkout@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}        
